### PR TITLE
Support for SwiftPM

### PR DESCRIPTION
**Pull request by mattmassicotte**
Hi Daniel,

This is a wonderfully simple solution you've put together - thank you!

What do you think about introducing support for some dependency management systems? I'm a Carthage user myself. But, Carthage requires introducing a Xcode project. I'd like to do this, but I thought perhaps a simpler first step might be better.

So, here's a simple set of changes to support SwiftPM. With this PR merged, you'd just need to publish an official Github release to allow others to install via SPM. What do you think?

One thing I didn't do, yet, was modify the README. It has a certain flow to it that I didn't want to mess up. Maybe I could get your input on that?

### CODE REVIEW

**Comment by danielpunkass** [comment]
Hi Matt! We were just talking about this on our latest Core Intuition, about how both Manton and I sort of laugh about single-file solutions like this having CocoaPods support. I did anticipate that maybe SwiftPM would be an appropriate option, so thanks for the PR! I'll take a closer look soon.

**Comment by mattmassicotte** [comment]
Heh, I'm behind in my listening, but I know what you mean. I'm not terribly familiar with CocoPods. But, SPM/Carthage is really just nice automation around integration and updating. Plus, it makes it trivial to expand past a single file, if there's ever the need.

No rush on looking though.

**Comment by mattmassicotte** [comment]
I finally got to listen to the episode you were referring to. I'm sorry that took so long - I'm so behind!

You and Manton both brought up some interesting points. They pretty much all centered around having trouble using CocoaPods. I've struggled a lot with CocoaPods myself. You both also brought up the issues around managing updates. For me, this is the key.

Do you use git submodules? Do you just copy-and-paste the file? I don't think supporting Swift PM takes away anything from those approaches. It just makes the work accessible to people that don't use those techniques. And, provides some super easy (and now Apple-supported!) automation around integrating changes.

**Comment by danielpunkass** [comment]
@mattmassicotte Thanks for listening! I don't use git submodules yet, but I will probably end up using them. I'm still largely rooted in Mercurial, but I don't even use Mercurial subrepos. I just have a bootstrap script basically for each of my projects that performs the equivalent of checking out the dependencies. I'm sure Swift PM will be compatible with this style of approach! Something like RSAppMovementMonitor is definitely a smaller-grained version of anything I would ever put in its own repository for my own sake. But who knows maybe if Swift PM pans out I'll end up being more comfortable doing that more often.

**Comment by danielpunkass** [comment]
I added a public release v1.0: https://github.com/redsweater/RSAppMovementMonitor/releases/tag/v1.0

Is there anything else I need to do practically, apart from updating the README to mention the SPM support? Can you help me with a brief synopsis of what it would  take to add this using SPM to another project?

**Comment by mattmassicotte** [comment]
Horray! To be honest, I wasn't sure how to interpret your response😅 Seems like I managed to wear you down!

I believe the release was all you needed to do. I was able to successfully add it to a test project via the Xcode UI:

Screen Shot 2019-10-31 at 1 45 44 PM

The UI did complain when I tried to use its version rules. But, to be honest, I do not understand how those work yet. I support SwiftPM for libraries in the same way, but I actually only use Carthage myself. This is going to be my first SwiftPM package!

**Comment by danielpunkass** [comment]
Hah! You didn't need to wear me down, I just had this on my back burner thinking I would learn more about SPM as part of the process. Decided just now it seemed pretty safe to merge the changes and learn more about SPM later :)

**Comment by mattmassicotte** [comment]
Ok good :)

Yeah, SPM is surprisingly unobtrusive. There are types of libraries/projects that it cannot describe that Carthage can (for now, anyways), but since you do not have a .xcodeproj for this, it would be harder to incorporate.

**Pull request merged**
